from __future__ import annotations

RETRIEVAL_MODE_STRUCTURED = 'structured'
RETRIEVAL_MODE_SEMANTIC = 'semantic'
RETRIEVAL_MODE_HYBRID = 'hybrid'

ALL_RETRIEVAL_MODES = (
    RETRIEVAL_MODE_STRUCTURED,
    RETRIEVAL_MODE_SEMANTIC,
    RETRIEVAL_MODE_HYBRID,
)
